Add
tomasloksa/azure-search-emulator pull request #52
Opened 2022-06-27 11:55 UTC by tomasloksa

+ Add support for upload (default) and mergeOrUpload of documents. In the current state the documents were always being overwritten and not specified properties were lost.
+ Add versioning and automated build/publish from preview branch
+ Fix and add postman tests

2022-06-27 11:57 UTC, tomasloksa commented on src/SearchQueryService/Controllers/SearchController.cs
> +        private JsonElement ConvertValue(JsonElement value)
This could probably be moved somewhere else, along with the `_valueReplacements`, but i couldn't figure out where.

2022-06-27 13:24 UTC, Burgyn requested changes

2022-06-28 06:32 UTC, Burgyn requested changes

2022-06-28 10:26 UTC, tomasloksa commented on .github/workflows/publish-search-docker-hub-preview.yml
> +name: Publish Search Emulator to Docker Hub
Predstavoval som si to tak, ze by PR chodili do preview a odtial az po otestovani by sa davali do mastra... alebo si skor narazal na to, ze sa to ma nejako oIFovat v tej jednej? nie som si isty, ci by to slo...

2022-08-03 08:28 UTC, merged