Fix search with empty field in filter
tomasloksa/azure-search-emulator pull request #60
Opened 2023-02-10 13:33 UTC by tomasloksa

+ replace `SomeProperty eq ''` with `-SomeProperty:['' TO *]` in filter
+ Create new PM tests for filters
+ Seed data in PM tests for consistent results and tidy up PM tests structure

2023-02-11 19:16 UTC, Burgyn requested changes
Nechceš rovno aj zvýšiť verziu?

2023-02-11 19:16 UTC, Burgyn commented on src/SearchQueryService/Services/SolrService.cs
> +            var test = _searchQueryBuilder.Build(indexName, searchParams);
Toto tu chceš nechať? 🙂

2023-02-13 06:51 UTC, tomasloksa commented on src/SearchQueryService/Services/SolrService.cs
> +            var test = _searchQueryBuilder.Build(indexName, searchParams);
nie, nechcem :D mal tam byť ešte jeden commit, ktorý som zabudol pushnúť

2023-02-13 09:44 UTC, Burgyn approved these changes

2023-02-13 09:45 UTC, merged